# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Angular app to Azure Web App - CanFlyFrontend

on:
  push:
    branches:
      - NetlifyDemoSite
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: |
            dist/**
            !node_modules/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: angular-app
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98A7DE3523CD4EFDAFF9FFB8B532AEAB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCED04112FB14D5286737E4CFA99CBF0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8536C39E90F148498AE8C5E1E0D2B6F8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'CanFlyFrontend'
          slot-name: 'Production'
          package: ./dist
